### ISSUE TITLE
Compilation error: "‘dof_’ was not declared in this scope"

### ISSUE THREAD

**Issue by kvasios** [google-research/tiny-differentiable-simulator#165]
The following error was thrown during compilation. (Ubuntu 20.04) 

/home/kvasios/tiny-differentiable-simulator/examples/../src/urdf/../multi_body.hpp:97:17: error: ‘dof_’ was not declared in this scope; did you mean ‘dof’?
   97 |     conv.dof_ = dof_;
      |                 ^~~~
      |                 dof
/home/kvasios/tiny-differentiable-simulator/examples/../src/urdf/../multi_body.hpp: In constructor ‘tds::MultiBody<Algebra>::MultiBody(const tds::MultiBody<AlgebraTo>&)’:
/home/kvasios/tiny-differentiable-simulator/examples/../src/urdf/../multi_body.hpp:371:9: error: class ‘tds::MultiBody<Algebra>’ does not have any field named ‘dof_’
  371 |         dof_(mb.dof_),
      |         ^~~~
make[2]: *** [examples/CMakeFiles/tiny_urdf_parser_example.dir/build.make:63: examples/CMakeFiles/tiny_urdf_parser_example.dir/tiny_urdf_parser_example.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:901: examples/CMakeFiles/tiny_urdf_parser_example.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:141: all] Error 2

**Comment by erwincoumans** [comment]
Thanks for the report. This should be fixed now, please try again.

**Comment by kvasios** [comment]
It works! Thanks!
