### ISSUE TITLE
compilation error- getting stuck

### ISSUE THREAD

**Issue by RupaliArtpark** [google-research/tiny-differentiable-simulator#168]
I git cloned the package Tiny Differentiable Simulator. Inside the package created a build directory.  Inside build as I execute 'make -j', my ubuntu freezes. I am using Ubuntu 20.04, gcc 11(supports cpp 17).  Am I doing something wrong?

**Comment by lasagnaphil** [comment]
This usually happens when your compiler eats up too much memory and the computer begins to use swap memory. Try lowering the core count for make (for example, make -j1 or make -j2)

**Comment by RupaliArtpark** [comment]
Hi Philsik,

Thanks for the suggestion. I will give it a try and let you know how it
goes.

Best Regards,
Rupali
