### ISSUE TITLE
Example run issue

### ISSUE THREAD

**Issue by RupaliArtpark** [google-research/tiny-differentiable-simulator#174]
After make -j step, the package is successfully compiling. The issue is with running scripts given in example. Every time I try to compile scripts in the example folder, the compiler is not able to find the existing header files. I tried providing path to the compiler for including header. Nothing works. Please help.
![Screenshot from 2021-10-13 12-42-55](https://user-images.githubusercontent.com/92155351/137086860-79261bd3-28e4-4c9c-909f-563d83241f05.png)

**Comment by erwincoumans** [comment]
You cannot run g++ as-is, you need to use the cmake generated projects.

**Comment by RupaliArtpark** [comment]
Hi,

It is after cmake and make -j I am trying to g++ the files. It's throwing
the same error.


Regards,
Rupali
